### ISSUE TITLE
Use `ByteBuffer` for `RESPValue` data storage

### ISSUE THREAD

**Issue by Mordil** [Mordil/nio-redis#31]
From the proposal discussion thread: https://forums.swift.org/t/discussion-nioredis-nio-based-redis-driver/22455/11

Change
```swift
public enum RESPValue {
    case .simpleString(String)
    case .bulkString([UInt8])
}
```
to
```swift
public enum RESPValue {
    case .simpleString(ByteBuffer)
    case .bulkString(ByteBuffer?)
}```

**Comment by tanner0101** [comment]
Big +1 to this. `ByteBuffer` slices are much cheaper to create than copying the bytes out into a `String` or `Array<UInt8>`. If the resulting data is ignored or discarded, then the copy doesn't need to take place at all which is a huge win.
